### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by gijsvantil** [legalclinic/privacyregister-standard#2]
@nwesterlaken Ik krijg onderstaande melding wanneer ik probeer te pushen. Zou jij kunnen checken of ik de juiste rechten heb om naar de repo te pushen, branches aan te maken, etc.?

> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

[Adding collaborators](https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/)

**Comment by nwesterlaken** [comment]
Goed, volgens mij heb je nu genoeg rechten voor die acties.
